name: "Build"
on:
  pull_request:
    paths-ignore:
      .github/settings.yml


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      push: false
