name: "Release"
on:
  push:
    branches: [main]
    paths-ignore:
      .github/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      push: true
